### ISSUE TITLE
Implement a Scrollable Message History and Layout Update with Draggable Dividers

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#144]
**Description:**
- **Objective:** Create a scrollable area to display past chat messages in the chat bar component, allowing users to review their conversation history. Ensure proper layout of the navbar, chatbar, and main content area in `mentus_tab.html` as per the specified design, including draggable dividers for adjustable width.
- **Requirements:**
  - Design a scrollable container in `chatbar.html`.
  - Style the container appropriately in `chatbar.css`.
  - Implement logic in `chatbar.js` to populate and maintain the message history.
  - Ensure the scrollable area is responsive and the chat bar height adjusts to the window height.
  - Update `mentus_tab.html` to properly layout the navbar, chatbar, and main content area, matching the annotated design.
  - Add draggable dividers between the left, center, and right sections to allow width adjustment.

**Acceptance Criteria:**
  - The message history container should be scrollable.
  - The container should display past messages correctly.
  - The design should be responsive and adapt to different screen sizes.
  - The chat bar should adjust its height to match the window height.
  - The `mentus_tab.html` layout should be functional and visually appealing, matching the annotated design.
  - Users should be able to adjust the width of the navigation bar, chat bar, and central content area using draggable dividers.

**File Modifications:**
- `components/chatbar/chatbar.html`
- `components/chatbar/chatbar.js`
- `components/chatbar/chatbar.css`
- `mentus_tab.html`
- `styles/main.css` (if needed for additional styling)
- `mentus_tab.js` (to implement draggable functionality)

**Details:**

1. **chatbar.html**:
   - Add a div element for the message history container.
     ```html
     <div id="messageContainer"></div>
     ```

2. **chatbar.css**:
   - Style the message container to be scrollable and ensure it adjusts to the window height.
     ```css
     #messageContainer {
       height: 100%;
       overflow-y: scroll;
       padding: 10px;
       border: 1px solid #ccc;
     }
     ```

3. **chatbar.js**:
   - Implement logic to populate the message history.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       const messageContainer = document.getElementById('messageContainer');
       
       // Sample messages to demonstrate functionality
       const messages = [
         "Hello, how can I assist you today?",
         "What are your learning goals?",
         "Let's explore some educational concepts together."
       ];

       messages.forEach(message => {
         const messageElement = document.createElement('div');
         messageElement.textContent = message;
         messageContainer.appendChild(messageElement);
       });
     });
     ```

4. **mentus_tab.html**:
   - Update the layout to properly display the navbar, chatbar, and main content area using `div` elements instead of `object` tags.
     ```html
     <!DOCTYPE html>
     <html>
     <head>
       <title>Mentus Tab</title>
       <link rel="stylesheet" type="text/css" href="../styles/main.css">
     </head>
     <body>
       <div id="navbar" class="navbar">
         <!-- Include the navbar component -->
         <div id="navbar-content"></div>
       </div>
       <div id="divider-left" class="divider"></div>
       <div id="main-content" class="main-content">
         <!-- Default to graphview, but allow switching to document view and editor view -->
         <div id="content-frame"></div>
       </div>
       <div id="divider-right" class="divider"></div>
       <div id="chatbar" class="chatbar">
         <!-- Include the chatbar component -->
         <div id="chatbar-content"></div>
       </div>
       <script src="mentus_tab.js"></script>
     </body>
     </html>
     ```

5. **mentus_tab.js**:
   - Implement draggable functionality for the dividers.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       const leftDivider = document.getElementById('divider-left');
       const rightDivider = document.getElementById('divider-right');
       let isDraggingLeft = false;
       let isDraggingRight = false;

       leftDivider.addEventListener('mousedown', () => isDraggingLeft = true);
       rightDivider.addEventListener('mousedown', () => isDraggingRight = true);
       
       document.addEventListener('mousemove', (e) => {
         if (isDraggingLeft) {
           document.getElementById('navbar').style.width = `${e.clientX}px`;
           document.getElementById('main-content').style.marginLeft = `${e.clientX + 5}px`;
         }
         if (isDraggingRight) {
           document.getElementById('chatbar').style.width = `${window.innerWidth - e.clientX}px`;
           document.getElementById('main-content').style.marginRight = `${window.innerWidth - e.clientX + 5}px`;
         }
       });

       document.addEventListener('mouseup', () => {
         isDraggingLeft = false;
         isDraggingRight = false;
       });

       document.getElementById('navbar-content').innerHTML = '<object type="text/html" data="../components/navbar/navbar.html" width="100%" height="100%"></object>';
       document.getElementById('chatbar-content').innerHTML = '<object type="text/html" data="../components/chatbar/chatbar.html" width="100%" height="100%"></object>';
       document.getElementById('content-frame').innerHTML = '<object type="text/html" data="../components/graphview/graphview.html" width="100%" height="100%"></object>';
     });
     ```

6. **main.css**:
   - Ensure the main CSS file properly styles the layout and the draggable dividers.
     ```css
     body {
       display: flex;
       height: 100vh;
       margin: 0;
     }

     .navbar {
       width: 20%;
       height: 100%;
     }

     .chatbar {
       width: 20%;
       height: 100%;
     }

     .main-content {
       flex: 1;
       height: 100%;
       overflow: auto;
     }

     .divider {
       width: 5px;
       cursor: ew-resize;
       background-color: #ccc;
     }

     #navbar-content, #chatbar-content, #content-frame {
       height: 100%;
     }

     object {
       width: 100%;
       height: 100%;
       border: none;
     }
     ```

**Contextual Information:**
- **Project Architecture:** The `chatbar` component is part of the Mentus Chrome extension. The main HTML template includes `chatbar.html` within the `#chatbar` div.
- **Relevant Files:**
  - `components/chatbar/chatbar.html`
  - `components/chatbar/chatbar.js`
  - `components/chatbar/chatbar.css`
  - `mentus_tab.html`
  - `styles/main.css`
