### ISSUE TITLE
Implement a Scrollable Message History and Layout Update with Tabs

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#148]
**Description:**
- **Objective:** Create a scrollable area to display past chat messages in the chat bar component, allowing users to review their conversation history. Ensure proper layout of the chatbar, main content area, and tabs for navigation between Graph, Docs, and Editor views. Adjust the colors to match the provided design.
- **Requirements:**
  - Design a scrollable container in `chatbar.html`.
  - Style the container appropriately in `chatbar.css`.
  - Implement logic in `chatbar.js` to populate and maintain the message history.
  - Ensure the scrollable area is responsive and the chat bar height adjusts to the window height.
  - Update `mentus_tab.html` to include tabs for navigation between Graph, Docs, and Editor views.
  - Adjust colors to match the provided screenshot.
  - Remove the vertical navbar and use tabs instead for navigation.

**Acceptance Criteria:**
  - The message history container should be scrollable.
  - The container should display past messages correctly.
  - The design should be responsive and adapt to different screen sizes.
  - The chat bar should adjust its height to match the window height.
  - The layout should match the design in the provided screenshot.
  - Users should be able to switch between Graph, Docs, and Editor views using tabs.

**File Modifications:**
- `components/chatbar/chatbar.html`
- `components/chatbar/chatbar.js`
- `components/chatbar/chatbar.css`
- `mentus_tab.html`
- `styles/main.css` (if needed for additional styling)
- `mentus_tab.js` (to implement tab functionality)

**Details:**

1. **chatbar.html**:
   - Add a div element for the message history container.
     ```html
     <div id="messageContainer"></div>
     ```

2. **chatbar.css**:
   - Style the message container to be scrollable and ensure it adjusts to the window height.
     ```css
     #messageContainer {
       height: 100%;
       overflow-y: scroll;
       padding: 10px;
       background-color: #333;
       color: #fff;
     }
     ```

3. **chatbar.js**:
   - Implement logic to populate the message history.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       const messageContainer = document.getElementById('messageContainer');
       
       // Sample messages to demonstrate functionality
       const messages = [
         "Hello, how can I assist you today?",
         "What are your learning goals?",
         "Let's explore some educational concepts together."
       ];

       messages.forEach(message => {
         const messageElement = document.createElement('div');
         messageElement.textContent = message;
         messageContainer.appendChild(messageElement);
       });
     });
     ```

4. **mentus_tab.html**:
   - Update the layout to properly display the chatbar on the left, and include tabs for navigation between Graph, Docs, and Editor views.
     ```html
     <!DOCTYPE html>
     <html>
     <head>
       <title>Mentus Tab</title>
       <link rel="stylesheet" type="text/css" href="../styles/main.css">
     </head>
     <body>
       <div class="container">
         <div id="chatbar" class="chatbar">
           <!-- Include the chatbar component -->
           <div id="chatbar-content"></div>
         </div>
         <div id="main-content" class="main-content">
           <div class="tabs">
             <button class="tab-button" onclick="showTab('graph')">Graph</button>
             <button class="tab-button" onclick="showTab('docs')">Docs</button>
             <button class="tab-button" onclick="showTab('editor')">Editor</button>
           </div>
           <div id="tab-content">
             <div id="graph" class="tab-content">Graph Content</div>
             <div id="docs" class="tab-content" style="display:none;">Docs Content</div>
             <div id="editor" class="tab-content" style="display:none;">Editor Content</div>
           </div>
         </div>
       </div>
       <script src="mentus_tab.js"></script>
     </body>
     </html>
     ```

5. **mentus_tab.js**:
   - Implement tab functionality to switch between Graph, Docs, and Editor views.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       document.getElementById('chatbar-content').innerHTML = '<object type="text/html" data="../components/chatbar/chatbar.html" width="100%" height="100%"></object>';
     });

     function showTab(tabName) {
       const tabs = document.getElementsByClassName('tab-content');
       for (let i = 0; i < tabs.length; i++) {
         tabs[i].style.display = 'none';
       }
       document.getElementById(tabName).style.display = 'block';
     }
     ```

6. **main.css**:
   - Ensure the main CSS file properly styles the layout and tabs.
     ```css
     body {
       display: flex;
       height: 100vh;
       margin: 0;
       overflow: hidden;
     }

     .container {
       display: flex;
       height: 100%;
       width: 100%;
     }

     .chatbar {
       width: 300px;
       height: 100%;
       background-color: #333;
       color: #fff;
     }

     .main-content {
       flex: 1;
       height: 100%;
       background-color: #222;
       color: #fff;
     }

     .tabs {
       display: flex;
       background-color: #444;
       padding: 10px;
     }

     .tab-button {
       background-color: #555;
       color: #fff;
       border: none;
       padding: 10px 20px;
       cursor: pointer;
     }

     .tab-button:hover {
       background-color: #666;
     }

     .tab-content {
       display: none;
       padding: 20px;
       background-color: #222;
     }

     #graph, #docs, #editor {
       display: none;
     }
     ```

**Contextual Information:**
- **Project Architecture:** The `chatbar` component is part of the Mentus Chrome extension. The main HTML template includes `chatbar.html` within the `#chatbar` div.
- **Relevant Files:**
  - `components/chatbar/chatbar.html`
  - `components/chatbar/chatbar.js`
  - `components/chatbar/chatbar.css`
  - `mentus_tab.html`
  - `styles/main.css`
