### ISSUE TITLE
Implement a Scrollable Message History and Layout Update with Tabs

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#150]
**Description:**
- **Objective:** Create a scrollable area to display past chat messages in the chat bar component, allowing users to review their conversation history. Ensure proper layout of the chatbar, main content area, and tabs for navigation between Graph, Docs, Editor, and Settings views. Adjust the colors to match the provided design.
- **Layout Details:**
  - The layout consists of a `chatbar` on the left, taking up 300px of the page width and extending the full height of the viewport.
  - The remaining space to the right is occupied by the `main-content` area.
  - The `main-content` area contains a `tabs` section at the top with buttons for "Graph", "Docs", "Editor", and "Settings".
  - Below the `tabs` section, the `tab-content` area will display the content corresponding to the selected tab.
  - The colors and styling should follow a dark theme, with the chatbar background color being #202225 and the main-content background color being #2F3136. The tab buttons should have a background color of #36393F and change to #484C52 on hover. The text color should be #DCDDDE.

**Requirements:**
  - Design a scrollable container in `chatbar.html`.
  - Style the container appropriately in `chatbar.css`.
  - Implement logic in `chatbar.js` to populate and maintain the message history.
  - Ensure the scrollable area is responsive and the chat bar height adjusts to the window height.
  - Update `mentus_tab.html` to include tabs for navigation between Graph, Docs, Editor, and Settings views.
  - Adjust colors to match the dark theme design.
  - Remove the vertical navbar and use tabs instead for navigation.

**Acceptance Criteria:**
  - The message history container should be scrollable.
  - The container should display past messages correctly.
  - The design should be responsive and adapt to different screen sizes.
  - The chat bar should adjust its height to match the window height.
  - The layout should match the described design.
  - Users should be able to switch between Graph, Docs, Editor, and Settings views using tabs.

**File Modifications:**
- `components/chatbar/chatbar.html`
- `components/chatbar/chatbar.js`
- `components/chatbar/chatbar.css`
- `components/tabs/settings/settings.html` (moved)
- `components/tabs/settings/settings.css` (moved)
- `components/tabs/settings/settings.js` (moved)
- `components/tabs/graphview/graphview.html` (moved)
- `components/tabs/graphview/graphview.css` (moved)
- `components/tabs/graphview/graphview.js` (moved)
- `components/tabs/documents/documents.html` (moved)
- `components/tabs/documents/documents.css` (moved)
- `components/tabs/documents/documents.js` (moved)
- `components/tabs/editor/editor.html` (moved)
- `components/tabs/editor/editor.css` (moved)
- `components/tabs/editor/editor.js` (moved)
- `mentus_tab.html`
- `mentus_tab.js`
- `styles/main.css` (if needed for additional styling)

**Details:**

1. **chatbar.html**:
   - Add a div element for the message history container.
     ```html
     <div id="messageContainer"></div>
     ```

2. **chatbar.css**:
   - Style the message container to be scrollable and ensure it adjusts to the window height.
     ```css
     #messageContainer {
       height: 100%;
       overflow-y: scroll;
       padding: 10px;
       background-color: #202225;
       color: #DCDDDE;
     }
     ```

3. **chatbar.js**:
   - Implement logic to populate the message history.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       const messageContainer = document.getElementById('messageContainer');
       
       // Sample messages to demonstrate functionality
       const messages = [
         "Hello, how can I assist you today?",
         "What are your learning goals?",
         "Let's explore some educational concepts together."
       ];

       messages.forEach(message => {
         const messageElement = document.createElement('div');
         messageElement.textContent = message;
         messageContainer.appendChild(messageElement);
       });
     });
     ```

4. **mentus_tab.html**:
   - Update the layout to properly display the chatbar on the left, and include tabs for navigation between Graph, Docs, Editor, and Settings views.
     ```html
     <!DOCTYPE html>
     <html>
     <head>
       <title>Mentus Tab</title>
       <link rel="stylesheet" type="text/css" href="../styles/main.css">
     </head>
     <body>
       <div class="container">
         <div id="chatbar" class="chatbar">
           <!-- Include the chatbar component -->
           <div id="chatbar-content"></div>
         </div>
         <div id="main-content" class="main-content">
           <div class="tabs">
             <button class="tab-button" onclick="showTab('graph')">Graph</button>
             <button class="tab-button" onclick="showTab('docs')">Docs</button>
             <button class="tab-button" onclick="showTab('editor')">Editor</button>
             <button class="tab-button" onclick="showTab('settings')">Settings</button>
           </div>
           <div id="tab-content">
             <div id="graph" class="tab-content">Graph Content</div>
             <div id="docs" class="tab-content" style="display:none;">Docs Content</div>
             <div id="editor" class="tab-content" style="display:none;">Editor Content</div>
             <div id="settings" class="tab-content" style="display:none;">Settings Content</div>
           </div>
         </div>
       </div>
       <script src="mentus_tab.js"></script>
     </body>
     </html>
     ```

5. **mentus_tab.js**:
   - Implement tab functionality to switch between Graph, Docs, Editor, and Settings views.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       document.getElementById('chatbar-content').innerHTML = '<object type="text/html" data="../components/chatbar/chatbar.html" width="100%" height="100%"></object>';
       document.getElementById('graph').innerHTML = '<object type="text/html" data="../components/tabs/graphview/graphview.html" width="100%" height="100%"></object>';
       document.getElementById('docs').innerHTML = '<object type="text/html" data="../components/tabs/documents/documents.html" width="100%" height="100%"></object>';
       document.getElementById('editor').innerHTML = '<object type="text/html" data="../components/tabs/editor/editor.html" width="100%" height="100%"></object>';
       document.getElementById('settings').innerHTML = '<object type="text/html" data="../components/tabs/settings/settings.html" width="100%" height="100%"></object>';
     });

     function showTab(tabName) {
       const tabs = document.getElementsByClassName('tab-content');
       for (let i = 0; i < tabs.length; i++) {
         tabs[i].style.display = 'none';
       }
       document.getElementById(tabName).style.display = 'block';
     }
     ```

6. **main.css**:
   - Ensure the main CSS file properly styles the layout and tabs.
     ```css
     body {
       display: flex;
       height: 100vh;
       margin: 0;
       overflow: hidden;
       background-color: #2F3136;
     }

     .container {
       display: flex;
       height: 100%;
       width: 100%;
     }

     .chatbar {
       width: 300px;
       height: 100%;
       background-color: #202225;
       color: #DCDDDE;
     }

     .main-content {
       flex: 1;
       height: 100%;
       background-color: #2F3136;
       color: #DCDDDE;
     }

     .tabs {
       display: flex;
       background-color: #36393F;
       padding: 10px;
     }

     .tab-button {
       background-color: #36393F;
       color: #DCDDDE;
       border: none;
       padding: 10px 20px;
       cursor: pointer;
       margin-right: 5px;
     }

     .tab-button:hover {
       background-color: #484C52;
     }

     .tab-content {
       display: none;
       padding: 20px;
       background-color: #2F3136;
     }

     #graph, #docs, #editor, #settings {
       display: none;
     }
     ```

Never attempt to install chrome for testing.
