### ISSUE TITLE
Add Missing Editor Tab, Improve Tab Layout, and Style Chat Window

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#152]
**Description:**
- **Objective:** Add the missing Editor tab, improve the layout of the tabs to ensure they are broad and evenly divide the available container, and style the chat window to match the main tab container.

**Requirements:**
  - Add the Editor tab to the tabs section in `mentus_tab.html`.
  - Update the CSS to ensure tabs are broad, evenly spaced, and well-aligned.
  - Ensure the tabs divide the available container space equally.
  - Style the chat window to match the colors and design of the main tab container.

**Acceptance Criteria:**
  - The Editor tab should be visible and functional.
  - Tabs should be broad, evenly spaced, and aligned.
  - The layout of the tabs should match the original design intentions.
  - The chat window should be styled to match the main tab container.

**File Modifications:**
- `components/tabs/editor/editor.html`
- `components/tabs/editor/editor.css`
- `components/tabs/editor/editor.js`
- `mentus_tab.html`
- `mentus_tab.js`
- `styles/main.css`
- `components/chatbar/chatbar.css`

**Details:**

1. **mentus_tab.html**:
   - Add the missing Editor tab to the tabs section.
     ```html
     <!DOCTYPE html>
     <html>
     <head>
       <title>Mentus Tab</title>
       <link rel="stylesheet" type="text/css" href="../styles/main.css">
     </head>
     <body>
       <div class="container">
         <div id="chatbar" class="chatbar">
           <!-- Include the chatbar component -->
           <div id="chatbar-content"></div>
         </div>
         <div id="main-content" class="main-content">
           <div class="tabs">
             <button class="tab-button" onclick="showTab('graph')">Graph</button>
             <button class="tab-button" onclick="showTab('docs')">Docs</button>
             <button class="tab-button" onclick="showTab('editor')">Editor</button>
             <button class="tab-button" onclick="showTab('settings')">Settings</button>
           </div>
           <div id="tab-content">
             <div id="graph" class="tab-content">Graph Content</div>
             <div id="docs" class="tab-content" style="display:none;">Docs Content</div>
             <div id="editor" class="tab-content" style="display:none;">Editor Content</div>
             <div id="settings" class="tab-content" style="display:none;">Settings Content</div>
           </div>
         </div>
       </div>
       <script src="mentus_tab.js"></script>
     </body>
     </html>
     ```

2. **mentus_tab.js**:
   - Ensure the Editor tab is correctly displayed and functional.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       document.getElementById('chatbar-content').innerHTML = '<object type="text/html" data="../components/chatbar/chatbar.html" width="100%" height="100%"></object>';
       document.getElementById('graph').innerHTML = '<object type="text/html" data="../components/tabs/graphview/graphview.html" width="100%" height="100%"></object>';
       document.getElementById('docs').innerHTML = '<object type="text/html" data="../components/tabs/documents/documents.html" width="100%" height="100%"></object>';
       document.getElementById('editor').innerHTML = '<object type="text/html" data="../components/tabs/editor/editor.html" width="100%" height="100%"></object>';
       document.getElementById('settings').innerHTML = '<object type="text/html" data="../components/tabs/settings/settings.html" width="100%" height="100%"></object>';
     });

     function showTab(tabName) {
       const tabs = document.getElementsByClassName('tab-content');
       for (let i = 0; i < tabs.length; i++) {
         tabs[i].style.display = 'none';
       }
       document.getElementById(tabName).style.display = 'block';
     }
     ```

3. **main.css**:
   - Update the CSS to ensure tabs are broad, evenly spaced, and well-aligned. Style the chat window to match the main tab container.
     ```css
     body {
       display: flex;
       height: 100vh;
       margin: 0;
       overflow: hidden;
       background-color: #2F3136;
     }

     .container {
       display: flex;
       height: 100%;
       width: 100%;
     }

     .chatbar {
       width: 300px;
       height: 100%;
       background-color: #202225;
       color: #DCDDDE;
     }

     .main-content {
       flex: 1;
       height: 100%;
       background-color: #2F3136;
       color: #DCDDDE;
     }

     .tabs {
       display: flex;
       background-color: #36393F;
       padding: 10px;
       justify-content: space-around;
     }

     .tab-button {
       background-color: #36393F;
       color: #DCDDDE;
       border: none;
       padding: 10px 20px;
       cursor: pointer;
       flex: 1;
       text-align: center;
     }

     .tab-button:hover {
       background-color: #484C52;
     }

     .tab-content {
       display: none;
       padding: 20px;
       background-color: #2F3136;
     }

     #graph, #docs, #editor, #settings {
       display: none;
     }
     ```

4. **chatbar.css**:
   - Ensure the chat window is styled to match the main tab container.
     ```css
     #messageContainer {
       height: 100%;
       overflow-y: scroll;
       padding: 10px;
       background-color: #202225;
       color: #DCDDDE;
     }

     .chatbar {
       background-color: #202225;
       color: #DCDDDE;
       border-right: 1px solid #484C52;
     }

     .chatbar input[type="text"], .chatbar button {
       background-color: #36393F;
       color: #DCDDDE;
       border: 1px solid #484C52;
     }

     .chatbar button {
       margin-top: 5px;
     }
     ```
