### ISSUE TITLE
Update Tab Layout, Style Chat Window, and Improve Main Content Area

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#154]
**Description:**
- **Objective:** Update the tab layout to be broad, evenly spaced, and well-aligned. Style the chat window to match the main tab container, and improve the main content area for better definition and accessibility of sections.

**Requirements:**
  - Update the CSS to ensure tabs are broad, evenly spaced, and well-aligned.
  - Ensure the tabs divide the available container space equally.
  - Style the chat window to match the colors and design of the main tab container.
  - Clearly define the main content area with a consistent background color.
  - Ensure sections (graph, docs, editor) are clearly separated and easily accessible.
  - Ensure consistent use of colors and fonts across the interface.
  - The file structure of the tabbed components (editor, settings, graph, and docs) should be moved under the `components/tabs/ folder

**Acceptance Criteria:**
  - Tabs should be broad, evenly spaced, and aligned.
  - The layout of the tabs should match the original design intentions.
  - The chat window should be styled to match the main tab container.
  - The main content area should be clearly defined and have a consistent background color.
  - Sections (graph, docs, editor) should be easily accessible and clearly separated.
  - The overall design should be clean and modern with consistent use of colors and fonts.

**File Modifications:**
- `mentus_tab.html`
- `mentus_tab.js`
- `styles/main.css`
- `components/chatbar/chatbar.css`

**Details:**

1. **mentus_tab.html**:
   - Update the layout to properly display the tabs and chat window.
     ```html
     <!DOCTYPE html>
     <html>
     <head>
       <title>Mentus Tab</title>
       <link rel="stylesheet" type="text/css" href="../styles/main.css">
     </head>
     <body>
       <div class="container">
         <div id="chatbar" class="chatbar">
           <!-- Include the chatbar component -->
           <div id="chatbar-content"></div>
         </div>
         <div id="main-content" class="main-content">
           <div class="tabs">
             <button class="tab-button" onclick="showTab('graph')">Graph</button>
             <button class="tab-button" onclick="showTab('docs')">Docs</button>
             <button class="tab-button" onclick="showTab('editor')">Editor</button>
             <button class="tab-button" onclick="showTab('settings')">Settings</button>
           </div>
           <div id="tab-content">
             <div id="graph" class="tab-content">Graph Content</div>
             <div id="docs" class="tab-content" style="display:none;">Docs Content</div>
             <div id="editor" class="tab-content" style="display:none;">Editor Content</div>
             <div id="settings" class="tab-content" style="display:none;">Settings Content</div>
           </div>
         </div>
       </div>
       <script src="mentus_tab.js"></script>
     </body>
     </html>
     ```

2. **mentus_tab.js**:
   - Ensure the tabs and chat window are correctly displayed and functional.
     ```javascript
     document.addEventListener("DOMContentLoaded", () => {
       document.getElementById('chatbar-content').innerHTML = '<object type="text/html" data="../components/chatbar/chatbar.html" width="100%" height="100%"></object>';
       document.getElementById('graph').innerHTML = '<object type="text/html" data="../components/tabs/graphview/graphview.html" width="100%" height="100%"></object>';
       document.getElementById('docs').innerHTML = '<object type="text/html" data="../components/tabs/documents/documents.html" width="100%" height="100%"></object>';
       document.getElementById('editor').innerHTML = '<object type="text/html" data="../components/tabs/editor/editor.html" width="100%" height="100%"></object>';
       document.getElementById('settings').innerHTML = '<object type="text/html" data="../components/tabs/settings/settings.html" width="100%" height="100%"></object>';
     });

     function showTab(tabName) {
       const tabs = document.getElementsByClassName('tab-content');
       for (let i = 0; i < tabs.length; i++) {
         tabs[i].style.display = 'none';
       }
       document.getElementById(tabName).style.display = 'block';
     }
     ```

3. **main.css**:
   - Update the CSS to ensure tabs are broad, evenly spaced, and well-aligned. Style the chat window to match the main tab container. Improve the definition of the main content area.
     ```css
     body {
       display: flex;
       height: 100vh;
       margin: 0;
       overflow: hidden;
       background-color: #2F3136;
     }

     .container {
       display: flex;
       height: 100%;
       width: 100%;
     }

     .chatbar {
       width: 300px;
       height: 100%;
       background-color: #202225;
       color: #DCDDDE;
       display: flex;
       flex-direction: column;
       justify-content: space-between;
     }

     #messageContainer {
       height: calc(100% - 60px); /* Adjust height to leave space for input */
       overflow-y: scroll;
       padding: 10px;
       background-color: #202225;
       color: #DCDDDE;
     }

     .chatbar input[type="text"], .chatbar button {
       background-color: #36393F;
       color: #DCDDDE;
       border: 1px solid #484C52;
       margin: 5px;
     }

     .chatbar button {
       margin-top: 5px;
     }

     .main-content {
       flex: 1;
       height: 100%;
       background-color: #2F3136;
       color: #DCDDDE;
     }

     .tabs {
       display: flex;
       background-color: #36393F;
       padding: 10px;
       justify-content: space-around;
     }

     .tab-button {
       background-color: #36393F;
       color: #DCDDDE;
       border: none;
       padding: 10px 20px;
       cursor: pointer;
       flex: 1;
       text-align: center;
     }

     .tab-button:hover {
       background-color: #484C52;
     }

     .tab-content {
       display: none;
       padding: 20px;
       background-color: #2F3136;
     }

     #graph, #docs, #editor, #settings {
       display: none;
     }
     ```

4. **chatbar.css**:
   - Ensure the chat window is styled to match the main tab container.
     ```css
     #messageContainer {
       height: 100%;
       overflow-y: scroll;
       padding: 10px;
       background-color: #202225;
       color: #DCDDDE;
     }

     .chatbar {
       background-color: #202225;
       color: #DCDDDE;
       border-right: 1px solid #484C52;
     }

     .chatbar input[type="text"], .chatbar button {
       background-color: #36393F;
       color: #DCDDDE;
       border: 1px solid #484C52;
       margin: 5px;
     }

     .chatbar button {
       margin-top: 5px;
     }
     ```

**Contextual Information:**
- **Project Architecture:** The `chatbar` component is part of the Mentus Chrome extension. The main HTML template includes `chatbar.html` within the `#chatbar` div.
- **Relevant Files:**
  - `components/tabs/editor/editor.html`
  - `components/tabs/editor/editor.css`
  - `components/tabs/editor/editor.js`
  - `mentus_tab.html`
  - `mentus_tab.js`
  - `styles/main.css`
  - `components/chatbar/chatbar.css`
