### ISSUE TITLE
Update Project to Fix Styling Issues and Make the Chatbar and Elements Match the Target Design

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#174]
**Description:**
- **Objective:** Fix the styling issues in `components/mentus_tab.html` to ensure the chatbar and other elements match the target design as shown in the second screenshot.

**Requirements:**
  - Update `mentus_tab.html` to ensure correct HTML structure and placement of elements.
  - Update `main.css` to ensure correct styling for the chatbar, input fields, buttons, and tabs.
  - Update `mentus_tab.js` to ensure the settings tab is displayed by default and the correct tab content is shown when a tab is clicked.

**Acceptance Criteria:**
  - The chatbar should have a dark background color and span the full height of the window.
  - The submit button should be correctly placed within the chat input container.
  - The tabs should be correctly styled and evenly spaced.
  - The settings tab should be displayed by default when the tab is opened.
  - Clicking on a tab should display the correct tab content.
  - The chat input and send button should be fixed at the bottom of the chat area.

**File Modifications:**

1. **Update `mentus_tab.html`:**

    ```html
    <!DOCTYPE html>
    <html>
    <head>
      <title>Mentus Tab</title>
      <link rel="stylesheet" type="text/css" href="../styles/main.css">
    </head>
    <body>
      <div class="container">
        <div id="chatbar" class="chatbar">
          <div id="chatbar-content">
            <div id="chat-messages" class="chat-messages"></div>
            <div class="chat-input-container">
              <input type="text" id="chat-input" placeholder="Type a message...">
              <button id="send-button">Send</button>
            </div>
          </div>
        </div>
        <div id="main-content" class="main-content">
          <div class="tabs">
            <button class="tab-button" data-tab="graph">Graph</button>
            <button class="tab-button" data-tab="docs">Docs</button>
            <button class="tab-button" data-tab="editor">Editor</button>
            <button class="tab-button" data-tab="settings">Settings</button>
          </div>
          <div id="tab-content">
            <div id="graph" class="tab-content">Graph Content</div>
            <div id="docs" class="tab-content" style="display:none;">Docs Content</div>
            <div id="editor" class="tab-content" style="display:none;">Editor Content</div>
            <div id="settings" class="tab-content" style="display:none;">Settings Content</div>
          </div>
        </div>
      </div>
      <script src="mentus_tab.js"></script>
    </body>
    </html>
    ```

2. **Update `main.css`:**

    ```css
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: #2e2e2e; /* Dark background color */
      color: #fff; /* Light text color */
    }

    .container {
      display: flex;
      height: 100vh;
    }

    .chatbar {
      background-color: #1e1e1e; /* Matching the darker background */
      width: 20%;
      display: flex;
      flex-direction: column;
      padding: 10px;
    }

    #chatbar-content {
      display: flex;
      flex-direction: column;
      height: 100%;
    }

    .chat-messages {
      flex: 1;
      overflow-y: auto;
    }

    .chat-input-container {
      display: flex;
      align-items: center;
      margin-top: 10px;
      padding: 10px 0;
      border-top: 1px solid #444;
    }

    #chat-input {
      flex: 1;
      padding: 5px;
      border: 1px solid #444;
      background-color: #333;
      color: #fff;
      margin-right: 10px;
    }

    #send-button {
      padding: 5px 10px;
      border: none;
      background-color: #444;
      color: #fff;
      cursor: pointer;
    }

    .main-content {
      flex: 1;
      padding: 20px;
    }

    .tabs {
      display: flex;
      justify-content: space-around;
      background-color: #1e1e1e;
      padding: 10px;
    }

    .tab-button {
      flex: 1;
      padding: 10px;
      background-color: #333;
      border: 1px solid #444;
      color: #fff;
      cursor: pointer;
      text-align: center;
    }

    .tab-content {
      display: none;
      padding: 20px;
      background-color: #2e2e2e;
    }

    .tab-content.active {
      display: block;
    }
    ```

3. **Update `mentus_tab.js` to Show Settings Tab by Default:**

    ```javascript
    document.addEventListener("DOMContentLoaded", () => {
      document.getElementById('chatbar-content').innerHTML = '<object type="text/html" data="../components/chatbar/chatbar.html" width="100%" height="100%"></object>';
      document.getElementById('graph').innerHTML = '<object type="text/html" data="../components/tabs/graphview/graphview.html" width="100%" height="100%"></object>';
      document.getElementById('docs').innerHTML = '<object type="text/html" data="../components/tabs/documents/documents.html" width="100%" height="100%"></object>';
      document.getElementById('editor').innerHTML = '<object type="text/html" data="../components/tabs/editor/editor.html" width="100%" height="100%"></object>';
      document.getElementById('settings').innerHTML = '<object type="text/html" data="../components/tabs/settings/settings.html" width="100%" height="100%"></object>';

      const tabButtons = document.querySelectorAll('.tab-button');
      tabButtons.forEach(button => {
        button.addEventListener('click', (event) => {
          const tabName = event.target.getAttribute('data-tab');
          showTab(tabName);
        });
      });

      function showTab(tabName) {
        const tabs = document.getElementsByClassName('tab-content');
        for (let i = 0; i < tabs.length; i++) {
          tabs[i].classList.remove('active');
        }
        document.getElementById(tabName).classList.add('active');
      }

      // Show the settings tab by default
      showTab('settings');
    });
    ```
