### ISSUE TITLE
Automate Testing with CI/CD

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#25]
### Automate Testing in CI/CD for Mentus Knowledge Instructor

**Objective:**
Implement automated testing for the Mentus Knowledge Instructor to ensure consistent and robust validation of functionality through continuous integration.

**Tasks:**

1. **Integrate Testing Frameworks:**
   - **Reason:** Combine Jest with Puppeteer for automated unit and browser testing to cover both backend logic and frontend interactions.
   - **Action:** Ensure Jest and Puppeteer are used as the testing frameworks.

2. **Install Necessary Dependencies:**
   - **Reason:** `jest`, `puppeteer`, and `jest-puppeteer` are essential for setting up and running the tests. `jest-puppeteer` specifically helps integrate Jest with Puppeteer.
   - **Action:** Add the following to `devDependencies` in `package.json`:
     - `jest`
     - `puppeteer`
     - `jest-puppeteer`

3. **Configure Jest:**
   - **Reason:** A configuration file is needed to tell Jest to use the `jest-puppeteer` preset, facilitating browser-based tests.
   - **Action:** Create a `jest.config.js` file with the following configuration:
     ```js
     module.exports = {
       preset: 'jest-puppeteer',
       testMatch: ['**/__tests__/**/*.js']
     };
     ```

4. **Develop Tests:**
   - **Reason:** Writing tests is crucial for validating the functionality of the Mentus Knowledge Instructor, ensuring it behaves as expected.
   - **Action:** Write and place tests in the `__tests__` directory. Ensure tests cover key functionalities and user interactions.

5. **Update `package.json` Scripts:**
   - **Reason:** Adding a test script to `package.json` allows for easy and consistent test execution.
   - **Action:** Ensure the `scripts` section in `package.json` includes:
     ```json
     "scripts": {
       "test": "jest"
     }
     ```

6. **Set Up CI/CD Pipeline:**
   - **Reason:** Automated testing in a CI/CD pipeline ensures code quality by running tests on every push and pull request.
   - **Action:** Create a GitHub Actions workflow (`.github/workflows/main.yml`) with the following steps:
     - Check out the repository.
     - Set up Node.js (use version 14).
     - Install dependencies.
     - Run the tests.
     
     Example:
     ```yaml
     name: Chrome Extension CI

     on: [push, pull_request]

     jobs:
       test:
         runs-on: ubuntu-latest

         steps:
         - uses: actions/checkout@v2
         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '14'
         - run: npm install
         - run: npm test
     ```

By completing these tasks, we will establish a robust automated testing setup that ensures the Mentus Knowledge Instructor functions correctly across all updates.

Thank you!
