### ISSUE TITLE
Automate Staging of Chrome Extension Using GitHub Releases

### ISSUE THREAD

**Issue by primed-lan-laucirica** [PrimeDeviation/mentus#32]
**Objective:**
Create a GitHub Actions workflow to automate the process of packaging the Chrome extension and uploading the zip file to GitHub Releases for staging purposes. This will allow us to prototype and test the extension before uploading it directly to the Chrome Web Store.

**Tasks:**

1. **Prepare Chrome Extension Build:**
   - **Reason:** Ensure that the Chrome extension is built and zipped correctly for staging.
   - **Action:** Verify that the build process generates a zip file of the Chrome extension.
   - **Details:** Ensure your `package.json` includes a script to build your extension. The build script should compile/transpile, bundle, minify, and copy files as needed for your project.

     Example `package.json`:
     ```json
     {
       "name": "my-chrome-extension",
       "version": "1.0.0",
       "scripts": {
         "build": "mkdir -p dist && cp -r src/* dist/" // Example build script
       },
       "devDependencies": {
         "jest": "^27.0.0",
         "puppeteer": "^10.0.0",
         "jest-puppeteer": "^6.0.0"
       }
     }
     ```

2. **Create GitHub Actions Workflow:**
   - **Reason:** Automate the build and deployment process using GitHub Actions.
   - **Action:** Create a GitHub Actions workflow file (`.github/workflows/release.yml`) with the following steps:
     - Check out the repository.
     - Set up Node.js (use version 14).
     - Install dependencies.
     - Build the Chrome extension.
     - Zip the built extension.
     - Create a GitHub Release and upload the zip file.

     Example Workflow:
     ```yaml
     name: Build and Release Chrome Extension

     on:
       push:
         tags:
           - 'v*.*.*'
       workflow_dispatch:

     jobs:
       build-and-release:
         runs-on: ubuntu-latest

         steps:
         - name: Check out the repository
           uses: actions/checkout@v2

         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '14'

         - name: Install dependencies
           run: npm install

         - name: Build the Chrome extension
           run: npm run build

         - name: Zip the extension
           run: zip -r chrome-extension.zip dist/*

         - name: Create Release
           id: create_release
           uses: actions/create-release@v1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
             tag_name: ${{ github.ref }}
             release_name: Release ${{ github.ref }}
             draft: false
             prerelease: false

         - name: Upload Release Asset
           uses: actions/upload-release-asset@v1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
             upload_url: ${{ steps.create_release.outputs.upload_url }}
             asset_path: ./chrome-extension.zip
             asset_name: chrome-extension.zip
             asset_content_type: application/zip
     ```

3. **Commit and Push Changes:**
   - **Reason:** Implementing the workflow in the repository ensures continuous integration and staging.
   - **Action:** Commit the workflow file and push it to the relevant branch.

4. **Create a New Tag:**
   - **Reason:** Trigger the release workflow by creating a new git tag.
   - **Action:** Create a new tag from your local repository and push it to GitHub.

     ```bash
     git tag v1.0.0
     git push origin v1.0.0
     ```

5. **Verify GitHub Actions:**
   - **Reason:** Ensure the workflow runs successfully and creates a release with the zip file attached.
   - **Action:** Monitor the workflow progress in the "Actions" tab of your GitHub repository.

6. **Verify Release:**
   - **Reason:** Confirm that the new release has been created and the zip file is attached.
   - **Action:** Go to the "Releases" section of your GitHub repository to verify.

By completing these tasks, we will automate the process of building the Chrome extension and uploading the zip file to GitHub Releases, allowing us to stage and test the extension before final deployment to the Chrome Web Store.
